# Generated by Django 4.0.4 on 2022-05-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField()),
                ('root_dir', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=50)),
            ],
        ),
    ]
