# Generated by Django 4.0.4 on 2022-05-09 17:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_rename_uploaded_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='root_dir',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='upload',
            name='document',
            field=models.FileField(default='xD', upload_to='uploads/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
