# Generated by Django 4.0.4 on 2022-05-09 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_remove_upload_root_dir_remove_upload_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.FileField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
