# Generated by Django 4.0.4 on 2022-05-09 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_alter_upload_document_alter_upload_file_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='output')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('original_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.upload')),
            ],
        ),
    ]
